### ISSUE TITLE
Ghosts Server Cleanup

### ISSUE THREAD

**Issue by pezhore** [cmu-sei/GHOSTS#126]
First off, love this project. It is exactly what we need for an upcoming Red v Blue event. We will absolutely be pointing attendees to this project at the conclusion of the event as a great resource to develop various skillsets.

The only issue we're seeing is that the ghosts server is filling up the file system (200GB in less than 24 hours). To be fair, we have ~30 ghost npcs performing actions on a regular interval, but I'm not sure if something is missing for clean up?

I've traced the largest overlay2 volume to the Ghosts-API container - it looks like the `merged/tmp` and `diff/tmp` folders are each consuming ~100GB. 

Is there something I can do to periodically do cleanup for Ghosts API to allow longer-running efforts?

Here is our docker-compose file:

```yaml
# docker-compose up -d
# -f compose-api.yml (if you want a custom file)
# The Grafana volume mounts assume the directory structure matches the git repository

version: '3.2'
networks:
  ghosts-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: ghosts-postgres
    environment:
      POSTGRES_DB: ghosts
      POSTGRES_USER: ghosts
      POSTGRES_PASSWORD: scotty@1
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./spectre_data:/tmp
    logging:
      options:
        max-size: '100m'
        max-file: '5'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ghosts']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ghosts-network
    restart: always

  ghosts-api:
    image: dustinupdyke/ghosts
    container_name: ghosts-api
    depends_on:
      - postgres
    ports:
      - '52388:5000'
    networks:
      - ghosts-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: ghosts-grafana
    user: root
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./g_data:/var/lib/grafana
      - ../../configuration/grafana/datasources:/etc/grafana/provisioning/datasources
      - ../../configuration/grafana/dashboards:/etc/grafana/provisioning/dashboards
```
