### ISSUE TITLE
Feature request: Add support for using YAML files for application and timeline configuration

### ISSUE THREAD

**Issue by it-ankka** [cmu-sei/GHOSTS#506]
Long and deeply nested JSON files become quite difficult to read and maintain. It is also very easy to accidentally miss a quotation mark or a bracket when writing raw JSON files by hand if you are not able to use the proper tooling.

For situations which require manual editing of the timeline and/or the application files, I would suggest adding support for using YAML to configure them. The main benefits of this I think would be increased readability, maintainability and conciseness.

JSON could still be used as the default format but it could be locally overridden by placing a .yaml or .yml file in the config folder. 

Libraries such as YamlDotNet should make this a fairly simple feature to add and I'd be willing to take a shot at implementing this myself.

Here is a small example of how a timeline configuration could look like in YAML compared to JSON

**YAML**

```yaml
status: Run
timeline_handlers:
  - handler_type: Command
    initial: ''
    utc_time_on: '00:00:00'
    utc_time_off: '24:00:00'
    loop: false
    timeline_events:
      - command: 'DIR c:\'
        command_args: []
        delay_after: 900000
        delay_before: 0
  - handler_type: Word
    initial: ''
    utc_time_on: '00:00:00'
    utc_time_off: '24:00:00'
    handler_args:
      working_set:
        max: 20
        max_age_in_hours: 72
    loop: true
    timeline_events:
      - command: create
        command_args:
          - '%homedrive%%homepath%\Documents'
          - pdf
          - pdf-vary-filenames
          - 'save-array:["c:\tmp", "c:\tmp\path2", "c:\tmp\path3"]'
        delay_after: 900000
        delay_before: 0
```

**JSON:**
```json
{
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Command",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "Loop": "False",
      "TimeLineEvents": [
        {
          "Command": "DIR c:\\",
          "CommandArgs": [
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ]
    },
    {
      "HandlerType": "Word",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "HandlerArgs": {
        "workingset": {
          "max": 20,
          "max-age-in-hours": 72
        }
      },
      "Loop": "True",
      "TimeLineEvents": [
        {
          "Command": "create",
          "CommandArgs": [ 
              "%homedrive%%homepath%\\Documents", 
              "pdf", 
              "pdf-vary-filenames", 
              "save-array:['c:\\tmp','c:\\tmp\\path2','c:\\tmp\\path3']" 
           ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ]
    }
  ]
}
```
